server:
    port: 8190

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    
sqs:
  queue:
    endpoint : https://sqs.us-east-1.amazonaws.com/355725938784/roshanQueue
    name: roshanQueue

aws:
  accesskey: AKIAISK3AUGUTCA 
  secretkey: xSSTY1vYP7/yPHCz4Y5XV1kesherO
